name: PUBG-Builder

on:
  push:
    branches: [main]
    tags: ['v*.*.*']
  pull_request:
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        os: [windows-latest]
        include:
        - os: windows-latest
          file: windows.Dockerfile
          tag: ${{ env.REGISTRY }}/${{ github.repository_owner }}/zk-builder-win:latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Log into registry ${{ env.REGISTRY }}
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker Build
      run: |
        docker build -f ${{ matrix.file }} -t ${{ matrix.tag }} -m 2GB .

    - name: Docker Push
      run: docker push ${{ matrix.tag }}
